spring:

# Redis
  redis:
    host: localhost
    port: 6380
  profiles:
    active: local

#Oracle
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: ###
    password: ###